services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672 # queue
      - 15672:15672 # UI management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BICO
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=$(POSTGRES_PORT)
      - POSTGRES_HOST=${POSTGRES_HOST}      
#    volumes:
#      - grafana_data:/var/lib/grafana

  listener:
    container_name: listener
    build: ./listener
    depends_on:
      - rabbitmq
    environment:
      - ALCHEMY_URL=${ALCHEMY_URL}
      - ENTRY_POINT_ADDRESS=${ENTRY_POINT_ADDRESS}

  consumer:
    container_name: consumer
    build: ./consumer
    depends_on:
      - rabbitmq
      - postgres
      - listener
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=$(POSTGRES_PORT)
      - POSTGRES_HOST=${POSTGRES_HOST}

  dashboard:
    container_name: dashboard
    build: ./dashboard
    depends_on:
      - grafana
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=$(POSTGRES_PORT)
      - POSTGRES_HOST=${POSTGRES_HOST}
volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_log:
#  grafana_data:
